language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  # - "2.6"


install:
  - pip install -e . --upgrade
  - pip install -r requirements.txt

script: py.test tests/