language: python
sudo: false
python:
  - 3.4
env:
  matrix:
    - TOXENV="py26"
    - TOXENV="py27"
    - TOXENV="py33"
    - TOXENV="py34"
    - TOXENV="py35"
    - TOXENV="pypy"

install: pip install tox==2.5.0
script: tox -e $TOXENV
